#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2015 by Tom Ting <tom_ting@realtek.com>
# 

obj-y	:= board.o
# 原有内容基础上添加spi_gpio_init.o
obj-y := board.o spi_gpio_init.o
